# config.yaml
defaults:
  - model: multimodal  # 确保这个目录和积木文件存在：model/multimodal.yaml
  - _self_

# 全局共享变量
global_dim: 16
num_classes: 4

# 训练相关的基础配置
train:
  batch_size: 2
  text_len: 3
  image_len: 2